# Generated by Django 5.0.4 on 2024-04-24 15:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('notes', '0003_alter_notes_file'),
    ]

    operations = [
        migrations.AlterField(
            model_name='notes',
            name='file',
            field=models.ImageField(blank=True, null=True, upload_to='user_images/'),
        ),
    ]
